// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPFnyLbNDTmkSYY8nhiMWpdf9olFIN_3o',
    appId: '1:140854816943:web:331dd2fb53959dd145e45a',
    messagingSenderId: '140854816943',
    projectId: 'bms-system-2499a',
    authDomain: 'bms-system-2499a.firebaseapp.com',
    storageBucket: 'bms-system-2499a.firebasestorage.app',
    measurementId: 'G-9RT2Q2QYTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHt_Em8MPR3v5X3TWRTdVGLWJRBkHMN34',
    appId: '1:140854816943:android:59028a4eae00a7a945e45a',
    messagingSenderId: '140854816943',
    projectId: 'bms-system-2499a',
    storageBucket: 'bms-system-2499a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAsWgFlog9-m1BVhLy6TM7jWCAf2gBZM',
    appId: '1:140854816943:ios:d1f25bc533ce6d1c45e45a',
    messagingSenderId: '140854816943',
    projectId: 'bms-system-2499a',
    storageBucket: 'bms-system-2499a.firebasestorage.app',
    iosBundleId: 'com.example.bms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAsWgFlog9-m1BVhLy6TM7jWCAf2gBZM',
    appId: '1:140854816943:ios:d1f25bc533ce6d1c45e45a',
    messagingSenderId: '140854816943',
    projectId: 'bms-system-2499a',
    storageBucket: 'bms-system-2499a.firebasestorage.app',
    iosBundleId: 'com.example.bms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPFnyLbNDTmkSYY8nhiMWpdf9olFIN_3o',
    appId: '1:140854816943:web:aaa3bebec525162945e45a',
    messagingSenderId: '140854816943',
    projectId: 'bms-system-2499a',
    authDomain: 'bms-system-2499a.firebaseapp.com',
    storageBucket: 'bms-system-2499a.firebasestorage.app',
    measurementId: 'G-XJ71F7SEYQ',
  );
}
